- name: Debian firewall
  hosts: debian
  sudo: true
  roles:
  - { role: debian, tags: debian, when: ansible_distribution == 'Debian' }

- name: FreeBSD firewall
  hosts: freebsd
  sudo: true
  roles:
  - { role: freebsd, tags: freebsd, when: ansible_distribution == 'FreeBSD' }
