- name: Disable ipfw
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^firewall_enable=
    line=firewall_enable=no
  notify: Stop ipfw
- name: Enable PF
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^pf_enable=
    line=pf_enable=YES
  notify: Reload pf
- name: Enable gateway
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^gateway_enable=
    line=gateway_enable=NO
  notify: Reload pf

- name: Paste pf config
  template: >
    src={{ ansible_hostname }}
    dest=/etc/pf.conf
    owner=root
    mode=0770
  notify: Reload pf
