- name: Enable firewall
  lineinfile: dest=/etc/rc.conf regexp=^firewall_enable= line=firewall_enable=YES
  notify: Reload ipfw
- name: Set firewall type
  lineinfile: dest=/etc/rc.conf regexp=^firewall_type= line=firewall_type=clossed
  notify: Reload ipfw
- name: Enable firewall logging
  lineinfile: dest=/etc/rc.conf regexp=^firewall_logging= line=firewall_logging=YES
  notify: Reload ipfw
- name: Set firewall script
  notify: Reload ipfw
  lineinfile: dest=/etc/rc.conf regexp=^firewall_script= line=firewall_script=/etc/ipfw.rules

- name: Paste ipfw config
  template:
    src={{ ansible_hostname }}
    dest=/etc/ipfw.rules
    owner=root
    mode=0770
  notify: Reload ipfw
